# Generated by Django 3.1.2 on 2020-10-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='zoom_host_id',
            field=models.CharField(default='invalid', max_length=256),
            preserve_default=False,
        ),
    ]
