# Generated by Django 3.1.2 on 2020-10-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20201027_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registrant_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
