# Generated by Django 3.1.2 on 2020-10-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_registration_registrant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registrant_id',
            field=models.CharField(max_length=256),
        ),
    ]
