# Generated by Django 3.1.2 on 2020-10-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20201027_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='zoom_id',
            field=models.CharField(default='-', max_length=256),
            preserve_default=False,
        ),
    ]
