# Generated by Django 3.1.2 on 2020-10-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_registration_zoom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='short_code',
            field=models.CharField(default='-', max_length=64),
            preserve_default=False,
        ),
    ]
