# Generated by Django 3.1.2 on 2020-10-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_meeting_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='breakouts_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
