# Generated by Django 3.1.2 on 2020-10-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_meeting_breakouts_frozen'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='x',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='y',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
