# Generated by Django 3.1.2 on 2021-03-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_auto_20201029_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='zoom_host_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='zoom_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registrant_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
