# Generated by Django 3.1.2 on 2021-04-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0014_meeting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='breakouts_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
