# Generated by Django 3.1.2 on 2021-04-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0015_meeting_breakouts_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='breakouts_transfer',
        ),
        migrations.AddField(
            model_name='meeting',
            name='manual_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
