# Generated by Django 3.1.2 on 2021-04-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0016_auto_20210422_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='zoom_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
