const emojis = [
  ["🎃", "Halloween"],
  ["😨", "Fearful Face"],
  ["😰", "Anxious Face with Sweat"],
  ["😱", "Face Screaming in Fear"],
  ["😈", "Smiling Face with Horns"],
  ["👿", "Angry Face with Horns"],
  ["💀", "Skull"],
  ["☠️", "Skull and Crossbones"],
  ["🤡", "Clown Face"],
  ["👹", "Ogre"],
  ["👺", "Goblin"],
  ["👻", "Ghost"],
  ["👽", "Alien"],
  ["👾", "Alien Monster"],
  ["🤖", "Robot"],
  ["🧡", "Orange Heart"],
  ["💚", "Green Heart"],
  ["🖤", "Black Heart"],
  ["🕵️", "Detective"],
  ["👸", "Princess"],
  ["🧙", "Mage"],
  ["🧚", "Fairy"],
  ["🧛", "Vampire"],
  ["🧜", "Merperson"],
  ["🧝", "Elf"],
  ["🧞", "Genie"],
  ["🧟", "Zombie"],
  ["🕴️", "Person in Suit Levitating"],
  ["🐈‍⬛", "Black Cat"],
  ["🦄", "Unicorn"],
  ["🦇", "Bat"],
  ["🦉", "Owl"],
  ["🕷️", "Spider"],
  ["🕸️", "Spider Web"],
  ["🥀", "Wilted Flower"],
  ["🍫", "Chocolate Bar"],
  ["🍬", "Candy"],
  ["🍭", "Lollipop"],
  ["🏚️", "Derelict House"],
  ["🌃", "Night with Stars"],
  ["🛸", "Flying Saucer"],
  ["🌕", "Full Moon"],
  ["🌚", "New Moon Face"],
  ["🌩️", "Cloud with Lightning"],
  ["⚡", "High Voltage"],
  ["🎃", "Jack-O-Lantern"],
  ["🔮", "Crystal Ball"],
  ["🎭", "Performing Arts"],
  ["🕯️", "Candle"],
  ["🗡️", "Dagger"],
  ["⛓️", "Chains"],
  ["🩸", "Drop Blood"],
  ["⚰️", "Coffin"],
  ["⚱️", "Funeral Urn"],
  ["🙈", "See-No-EvilMonkey"],
  ["🙉", "Hear-No-Evil Monkey"],
  ["🙊", "Speak-No-Evil Monkey"],
  ["💥", "Collision"],
  ["💫", "Dizzy"],
  ["💦", "Sweat Droplets"],
  ["💨", "Dashing Away"],
  ["🐵", "Monkey Face"],
  ["🐒", "Monkey"],
  ["🦍", "Gorilla"],
  ["🦧", "Orangutan"],
  ["🐶", "Dog Face"],
  ["🐕", "Dog"],
  ["🐩", "Poodle"],
  ["🐺", "Wolf"],
  ["🦊", "Fox"],
  ["🦝", "Raccoon"],
  ["🐱", "Cat Face"],
  ["🐈", "Cat"],
  ["🦁", "Lion"],
  ["🐯", "Tiger Face"],
  ["🐅", "Tiger"],
  ["🐆", "Leopard"],
  ["🐴", "Horse Face"],
  ["🐎", "Horse"],
  ["🦄", "Unicorn"],
  ["🦓", "Zebra"],
  ["🦌", "Deer"],
  ["🐮", "Cow Face"],
  ["🐂", "Ox"],
  ["🐃", "Water Buffalo"],
  ["🐄", "Cow"],
  ["🐷", "Pig Face"],
  ["🐖", "Pig"],
  ["🐗", "Boar"],
  ["🐽", "Pig Nose"],
  ["🐏", "Ram"],
  ["🐑", "Ewe"],
  ["🐐", "Goat"],
  ["🐪", "Camel"],
  ["🐫", "Two-Hump Camel"],
  ["🦙", "Llama"],
  ["🦒", "Giraffe"],
  ["🐘", "Elephant"],
  ["🦏", "Rhinoceros"],
  ["🦛", "Hippopotamus"],
  ["🐭", "Mouse Face"],
  ["🐁", "Mouse"],
  ["🐀", "Rat"],
  ["🐹", "Hamster"],
  ["🐰", "Rabbit Face"],
  ["🐇", "Rabbit"],
  ["🐿️", "Chipmunk"],
  ["🦔", "Hedgehog"],
  ["🦇", "Bat"],
  ["🐻", "Bear"],
  ["🐻‍❄️", "Polar Bear"],
  ["🐨", "Koala"],
  ["🐼", "Panda"],
  ["🦥", "Sloth"],
  ["🦦", "Otter"],
  ["🦨", "Skunk"],
  ["🦘", "Kangaroo"],
  ["🦡", "Badger"],
  ["🐾", "Paw Prints"],
  ["🦃", "Turkey"],
  ["🐔", "Chicken"],
  ["🐓", "Rooster"],
  ["🐣", "Hatching Chick"],
  ["🐤", "Baby Chick"],
  ["🐥", "Front-Facing Baby Chick"],
  ["🐦", "Bird"],
  ["🐧", "Penguin"],
  ["🕊️", "Dove"],
  ["🦅", "Eagle"],
  ["🦆", "Duck"],
  ["🦢", "Swan"],
  ["🦉", "Owl"],
  ["🦩", "Flamingo"],
  ["🦚", "Peacock"],
  ["🦜", "Parrot"],
  ["🐸", "Frog"],
  ["🐊", "Crocodile"],
  ["🐢", "Turtle"],
  ["🦎", "Lizard"],
  ["🐍", "Snake"],
  ["🐲", "Dragon Face"],
  ["🐉", "Dragon"],
  ["🦕", "Sauropod"],
  ["🦖", "T-Rex"],
  ["🐳", "Spouting Whale"],
  ["🐋", "Whale"],
  ["🐬", "Dolphin"],
  ["🐟", "Fish"],
  ["🐠", "Tropical Fish"],
  ["🐡", "Blowfish"],
  ["🦈", "Shark"],
  ["🐙", "Octopus"],
  ["🐚", "Spiral Shell"],
  ["🐌", "Snail"],
  ["🦋", "Butterfly"],
  ["🐛", "Bug"],
  ["🐜", "Ant"],
  ["🐝", "Honeybee"],
  ["🐞", "Lady Beetle"],
  ["🦗", "Cricket"],
  ["🕷️", "Spider"],
  ["🕸️", "Spider Web"],
  ["🦂", "Scorpion"],
  ["🦟", "Mosquito"],
  ["🦠", "Microbe"],
  ["💐", "Bouquet"],
  ["🌸", "Cherry Blossom"],
  ["💮", "White Flower"],
  ["🏵️", "Rosette"],
  ["🌹", "Rose"],
  ["🥀", "Wilted Flower"],
  ["🌺", "Hibiscus"],
  ["🌻", "Sunflower"],
  ["🌼", "Blossom"],
  ["🌷", "Tulip"],
  ["🌱", "Seedling"],
  ["🌲", "Evergreen Tree"],
  ["🌳", "Deciduous Tree"],
  ["🌴", "Palm Tree"],
  ["🌵", "Cactus"],
  ["🌾", "Sheaf of Rice"],
  ["🌿", "Herb"],
  ["☘️", "Shamrock"],
  ["🍀", "Four Leaf Clover"],
  ["🍁", "Maple Leaf"],
  ["🍂", "Fallen Leaf"],
  ["🍃", "Leaf Fluttering in Wind"],
  ["🍄", "Mushroom"],
  ["🌰", "Chestnut"],
  ["🦀", "Crab"],
  ["🦞", "Lobster"],
  ["🦐", "Shrimp"],
  ["🦑", "Squid"],
  ["🌈", "Rainbow"],
  ["☂️", "Umbrella"],
  ["☔", "Umbrella with Rain Drops"],
  ["⚡", "High Voltage"],
  ["❄️", "Snowflake"],
  ["☃️", "Snowman"],
]

export function randomEmoji(){
  const index = Math.floor(Math.random()*emojis.length);
  return emojis[index][0];
};
