# Generated by Django 3.1.2 on 2020-10-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZoomUser',
            new_name='ZoomUserToken',
        ),
    ]
