# Generated by Django 3.1.2 on 2020-10-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_auto_20201026_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomusertoken',
            name='zoom_api_data',
            field=models.TextField(default='{}'),
        ),
    ]
