---
- name: unbreakout-unzoom
  hosts: unbreakout-unzoom
  become: yes
  become_method: sudo
  vars_files: 
  - vars/unbreakout.unhangout.io.yml
  roles:
  - common
  - users
  - swap
  - docker-ubuntu
  - nginx-proxy
  - redis
  - postgres
  - role: postgres-role
    vars:
      DB_NAME: "{{django_postgres_db}}"
      DB_USER: "{{django_postgres_user}}"
      DB_PASSWORD: "{{django_postgres_password}}"
  - role: build-docker-image
    vars:
      GIT_REPO: https://github.com/mitmedialab/unbreakout.git
      CODE_VERSION: "unzoom"
    tags: ['django-app']
  - role: django-app
    tags: ['django-app']
